### ISSUE TITLE
PHP version_compare 

### ISSUE THREAD

**Issue by tremer-m** [dewawi/dewawi#21]
Hi,

after installing the application I receive the following error message: 

Fatal error: Uncaught ValueError: version_compare(): Argument #3 ($operator) must be a valid comparison operator in /home/webpages/lima-city/destillerie/wawi/library/Zend/Xml/Security.php:172 Stack trace: #0 /home/webpages/lima-city/destillerie/wawi/library/Zend/Xml/Security.php(172): version_compare('8.3.2', '5.6', 'gte') #1 /home/webpages/lima-city/destillerie/wawi/library/Zend/Xml/Security.php(76): Zend_Xml_Security::isPhpFpm() #2 /home/webpages/lima-city/destillerie/wawi/library/Zend/Xml/Security.php(150): Zend_Xml_Security::scan('<?xml version="...', NULL) #3 /home/webpages/lima-city/destillerie/wawi/library/Zend/Locale/Data.php(160): Zend_Xml_Security::scanFile('/home/webpages/...') #4 /home/webpages/lima-city/destillerie/wawi/library/Zend/Locale/Data.php(232): Zend_Locale_Data::_findRoute('supplementalDat...', '/supplementalDa...', 'iso4217', 'DE', Array) #5 /home/webpages/lima-city/destillerie/wawi/library/Zend/Locale/Data.php(1279): Zend_Locale_Data::_getFile('supplementalDat...', '/supplementalDa...', 'iso4217', 'DE') #6 /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php(323): Zend_Locale_Data::getContent('de_DE', 'currencytoregio...', 'DE') #7 /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php(375): Zend_Currency->_checkParams(NULL, 'de_DE') #8 /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php(569): Zend_Currency->getShortName(NULL, 'de_DE') #9 /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php(100): Zend_Currency->setLocale('de_DE') #10 /home/webpages/lima-city/destillerie/wawi/application/Bootstrap.php(92): Zend_Currency->__construct(Array) #11 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(681): Bootstrap->_initLocale() #12 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(634): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('locale') #13 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('locale') #14 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application.php(373): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL) #15 /home/webpages/lima-city/destillerie/wawi/index.php(56): Zend_Application->bootstrap() #16 {main} thrown in /home/webpages/lima-city/destillerie/wawi/library/Zend/Xml/Security.php on line 172

I think there is a bug in the file /Security.php 

How can I fix this?

Thanks,
Michael

**Comment by tremer-m** [comment]
Hi, I did install now the release 1.1.0 and now I receive a new error message: 

Fatal error: Uncaught Zend_Currency_Exception: No region found within the locale '' in /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php:559 Stack trace: #0 /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php(100): Zend_Currency->setLocale('') #1 /home/webpages/lima-city/destillerie/wawi/application/Bootstrap.php(92): Zend_Currency->__construct(Array) #2 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(673): Bootstrap->_initLocale() #3 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(626): Zend_Application_Bootstrap_BootstrapAbstract->_executeResource('locale') #4 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application/Bootstrap/BootstrapAbstract.php(590): Zend_Application_Bootstrap_BootstrapAbstract->_bootstrap('locale') #5 /home/webpages/lima-city/destillerie/wawi/library/Zend/Application.php(389): Zend_Application_Bootstrap_BootstrapAbstract->bootstrap(NULL) #6 /home/webpages/lima-city/destillerie/wawi/index.php(56): Zend_Application->bootstrap() #7 {main} thrown in /home/webpages/lima-city/destillerie/wawi/library/Zend/Currency.php on line 559

**Comment by tremer-m** [comment]
Hi, for this instance 8,2 PHP-fpm

**Comment by kseones** [comment]
Reported the issue to zf1-future: https://github.com/Shardj/zf1-future/issues/425
